[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Permissions-Policy = "camera=(), microphone=()"
    # Do NOT set X-Frame-Options/CSP frame-ancestors here; Telegram opens a webview, not an iframe.

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-store"
